services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: quant_advisor
      POSTGRES_USER: qa
      POSTGRES_PASSWORD: qa
    ports:
      - "5432:5432"
    volumes:
      - qa_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - qa_redis:/data

volumes:
  qa_postgres:
  qa_redis:


